import type { GetServerSideProps } from 'next'
import Head from 'next/head'
import { Grid } from '@chakra-ui/react'
import Sidebar from '../components/Sidebar'
import Feed from '../components/Feed'
import Widgets from '../components/Widgets'
import { fetchTweets } from '../utils/fetchTweets'
import { Tweet } from '../types/type'

interface Props {
  tweets: Tweet[]
}

const Home = ({ tweets }: Props) => {
  return (
    <>
      <Head>
        <title>Welcome to My Twitter Clone</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Grid
          templateColumns='repeat(9, 1fr)'
          maxW='container.xl'
          mx='auto'
          maxH='100%'
          overflow='hidden'
        >
          <Sidebar />
          <Feed tweets={tweets}/>
          <Widgets />
        </Grid>
      </main>
    </>
  )
}

export default Home

export const getServerSideProps: GetServerSideProps = async (context) => {
  const tweets = await fetchTweets()
  return {
    props: {
      tweets,
    },
  }
}
